---
- name: restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted

- name: restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted

- name: restart hostapd
  ansible.builtin.systemd:
    name: hostapd
    state: restarted

- name: reload systemd + restart hostapd
  ansible.builtin.systemd:
    daemon_reload: true
    name: hostapd
    state: restarted

- name: restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
